POST http://localhost:3000/users/register
Content-Type: application/json

{
    "email": "diego.aranda2@live.u-tad.com",
    "password": "12345678"
}
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "diego.aranda2@live.u-tad.com",
    "password": "12345678"
}


###
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "email": "hola@gmail.com",
    "password": "123123123"
}

###
PUT http://localhost:3000/users/validate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U3ZjNiMWJhYTI0Y2E0YzliYWExZmIiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMjU0NDQ5LCJleHAiOjE3NDMyNTgwNDl9.gkEP7aZxiwDmNcEINbDkiJQXW7g8igP-MemFe4otAjg


{
    "code": "173244"
}
###
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "email": "daina@gmail.com",
    "password": "holaholaa"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "daina@gmail.com",
    "password": "holaholaa"
}