POST http://localhost:3000/users/register
Content-Type: application/json

{
    "email": "diego.aranda2@live.u-tad.com",
    "password": "12345678"
}
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "diego.aranda2@live.u-tad.com",
    "password": "12345678"
}


###
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "email": "hola@gmail.com",
    "password": "123123123"
}

###
PUT http://localhost:3000/users/validate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U4NmFiNDg0MWM1NjQ5ZWNmNmMzNTgiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMjg0OTE2LCJleHAiOjE3NDMyODg1MTZ9.LibQb4KibwKcPSr4MLTzkizzRFlNstftkKN-wZ9FOVQ


{
    "code": "107007"
}
###
POST http://localhost:3000/users/register
Content-Type: application/json

{
    "email": "daina@gmail.com",
    "password": "holaholaa"
}

###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "daina@gmail.com",
    "password": "holaholaa"
}


###
PUT http://localhost:3000/users/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U4NmFiNDg0MWM1NjQ5ZWNmNmMzNTgiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMzMwMDk5LCJleHAiOjE3NDMzMzM2OTl9.BEnAQ-3157DibUF530daiabULuC4G3cpcRyHThuu-pA


{
    "email": "diego.aranda2@live.u-tad.com",
    "name": "Diego",
    "surnames":"Aranda",
    "nif":"18456604R"
}


###
PUT http://localhost:3000/users/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U4NmFiNDg0MWM1NjQ5ZWNmNmMzNTgiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMzMwMDk5LCJleHAiOjE3NDMzMzM2OTl9.BEnAQ-3157DibUF530daiabULuC4G3cpcRyHThuu-pA

{
    "company": {
        "name": "Servitop, SL.",
        "cif": "B12345678",
        "street": "Carlos V",
        "number": 22,
        "postal": 28936,
        "city": "Móstoles",
        "province": "Madrid"
    }
}


###
PUT http://localhost:3000/users/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U5NjY2NDJjMTkwOTU5MGUxNmQ0NDEiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMzQ5MzQ5LCJleHAiOjE3NDMzNTI5NDl9.YW2rh5hfJ_KVCoHe9pP8MJM4xLCfF9HuuXZj50mlnyQ

{
    "company": {
        "name": "Servitop, SL.",
        "cif": "B12345678",
        "street": "Carlos V",
        "number": 22,
        "postal": 28936,
        "city": "Móstoles",
        "province": "Madrid"
    }
}


###
GET http://localhost:3000/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U5NjY2NDJjMTkwOTU5MGUxNmQ0NDEiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMzQ5MzQ5LCJleHAiOjE3NDMzNTI5NDl9.YW2rh5hfJ_KVCoHe9pP8MJM4xLCfF9HuuXZj50mlnyQ

###
DELETE http://localhost:3000/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U4NmFiNDg0MWM1NjQ5ZWNmNmMzNTgiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMzMwMDk5LCJleHAiOjE3NDMzMzM2OTl9.BEnAQ-3157DibUF530daiabULuC4G3cpcRyHThuu-pA

###
DELETE http://localhost:3000/users/?soft=false
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U4NmFiNDg0MWM1NjQ5ZWNmNmMzNTgiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMzMwMDk5LCJleHAiOjE3NDMzMzM2OTl9.BEnAQ-3157DibUF530daiabULuC4G3cpcRyHThuu-pA

###
PATCH http://localhost:3000/users/logo HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U5NjY2NDJjMTkwOTU5MGUxNmQ0NDEiLCJyb2xlIjpbInVzZXIiXSwiaWF0IjoxNzQzMzQ5MzQ5LCJleHAiOjE3NDMzNTI5NDl9.YW2rh5hfJ_KVCoHe9pP8MJM4xLCfF9HuuXZj50mlnyQ

--boundary123
Content-Disposition: form-data; name="image"; filename="Raccoon.jpg"
Content-Type: image/jpeg

< Raccoon.jpg
--boundary123--